# Generated by Django 4.0.3 on 2022-05-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_profile_email_remove_profile_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to=''),
        ),
    ]
