# Generated by Django 4.0.3 on 2022-05-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
