# Generated by Django 4.0.3 on 2022-07-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='push_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
