# Generated by Django 4.0.3 on 2022-07-22 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
